v02/config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  resources :speakers
  resources :events
  resources :organizers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

v02/app/models/speaker.rb
class Speaker < ApplicationRecord
  has_many :sessions
end

v02/app/controllers/speakers_controller.rb
class SpeakersController < ApplicationController
  before_action :set_speaker, only: [:show, :edit, :update, :destroy]

  # GET /speakers
  # GET /speakers.json
  def index
    @speakers = Speaker.all
  end

  # GET /speakers/1
  # GET /speakers/1.json
  def show
  end

  # GET /speakers/new
  def new
    @speaker = Speaker.new
  end

  # GET /speakers/1/edit
  def edit
  end

  # POST /speakers
  # POST /speakers.json
  def create
    @speaker = Speaker.new(speaker_params)

    respond_to do |format|
      if @speaker.save
        format.html { redirect_to @speaker, notice: 'Speaker was successfully created.' }
        format.json { render :show, status: :created, location: @speaker }
      else
        format.html { render :new }
        format.json { render json: @speaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /speakers/1
  # PATCH/PUT /speakers/1.json
  def update
    respond_to do |format|
      if @speaker.update(speaker_params)
        format.html { redirect_to @speaker, notice: 'Speaker was successfully updated.' }
        format.json { render :show, status: :ok, location: @speaker }
      else
        format.html { render :edit }
        format.json { render json: @speaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /speakers/1
  # DELETE /speakers/1.json
  def destroy
    @speaker.destroy
    respond_to do |format|
      format.html { redirect_to speakers_url, notice: 'Speaker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_speaker
      @speaker = Speaker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def speaker_params
      params.require(:speaker).permit(:first_name, :last_name, :birth_year)
    end
end

v02/app/helpers/speakers_helper.rb
module SpeakersHelper
end

v02/app/views/speakers/_form.html.erb
<%= form_with(model: speaker, local: true) do |form| %>
  <% if speaker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(speaker.errors.count, "error") %> prohibited this speaker from being saved:</h2>

      <ul>
      <% speaker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :speaker_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :speaker_last_name %>
  </div>

  <div class="field">
    <%= form.label :birth_year %>
    <%= form.text_field :birth_year, id: :speaker_birth_year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

v02/app/views/speakers/edit.html.erb
<h1>Editing Speaker</h1>

<%= render 'form', speaker: @speaker %>

<%= link_to 'Show', @speaker %> |
<%= link_to 'Back', speakers_path %>

v02/app/views/speakers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Speakers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Birth year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @speakers.each do |speaker| %>
      <tr>
        <td><%= speaker.first_name %></td>
        <td><%= speaker.last_name %></td>
        <td><%= speaker.birth_year %></td>
        <td><%= link_to 'Show', speaker %></td>
        <td><%= link_to 'Edit', edit_speaker_path(speaker) %></td>
        <td><%= link_to 'Destroy', speaker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Speaker', new_speaker_path %>

v02/app/views/speakers/new.html.erb
<h1>New Speaker</h1>

<%= render 'form', speaker: @speaker %>

<%= link_to 'Back', speakers_path %>

v02/app/views/speakers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @speaker.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @speaker.last_name %>
</p>

<p>
  <strong>Birth year:</strong>
  <%= @speaker.birth_year %>
</p>

<%= link_to 'Edit', edit_speaker_path(@speaker) %> |
<%= link_to 'Back', speakers_path %>